# Generated by Django 3.0.7 on 2020-09-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajibadeolufemi94scrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumyhistory',
            name='time_of_action',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
